fullscreen=true
logfile = true
gameName = "PhantomDogs"
gameDesc = "A reimplementation of Nancy Drew 7"
windowWidth = 1280
windowHeight = 720
referenceWidth = 800
referenceHeight = 600
globalScale = 1.25

[debug]
debugHot = true
debugNoSound = false
debugMenuOpen = false
lograw = true