fullscreen=false
logfile = true
gameName = "Phantom Dogs"
gameDesc = "A reimplementation of Nancy Drew 7"
windowWidth = 960
windowHeight = 544
referenceWidth = 800
referenceHeight = 600
globalScale = 1.25

[debug]
debugHot = true
debugNoSound = false
debugMenuEnabled = true
lograw = true