fullscreen=false
logfile = true
gameName = "Phantom Dogs"
gameDesc = "A reimplementation of Nancy Drew 7"
windowWidth = 800
windowHeight = 600
referenceWidth = 800
referenceHeight = 600
globalScale = 1.25

[debug]
debugHot = true
debugNoSound = true
debugMenuEnabled = true
logRaw = true
logLevel = "ERROR"